export const CREATE_ASSISTANT = "CREATE_ASSISTANT";

export const POST_REGISTRATION_BEGIN = "POST_REGISTRATION_BEGIN";
export const POST_REGISTRATION_SUCCESS = "POST_REGISTRATION_SUCCESS";
export const POST_REGISTRATION_ERROR = "POST_REGISTRATION_ERROR";
