export const CREATE_ASSISTANT = "CREATE_ASSISTANT";

export const GET_ASSISTANTS_BEGIN = "GET_ASSISTANTS_BEGIN";
export const GET_ASSISTANTS_SUCCESS = "GET_ASSISTANTS_SUCCESS";
export const GET_ASSISTANTS_ERROR = "GET_ASSISTANTS_ERROR";
export const EDIT_ASSISTANT_START = "EDIT_ASSISTANT_START";
export const EDIT_ASSISTANT_END = "EDIT_ASSISTANT_END";
export const SUBMIT_ASSISTANT_BEGIN = "SUBMIT_ASSISTANT_BEGIN";
export const SUBMIT_ASSISTANT_SUCCESS = "SUBMIT_ASSISTANT_SUCCESS";
export const SUBMIT_ASSISTANT_ERROR = "SUBMIT_ASSISTANT_ERROR";

export const GET_WORK_SHIFTS_BEGIN = "GET_WORK_SHIFTS_BEGIN";
export const GET_WORK_SHIFTS_SUCCESS = "GET_WORK_SHIFTS_SUCCESS";
export const GET_WORK_SHIFTS_ERROR = "GET_WORK_SHIFTS_ERROR";
export const EDIT_WORK_SHIFT_START = "EDIT_WORK_SHIFT_START";
export const EDIT_WORK_SHIFT_END = "EDIT_WORK_SHIFT_END";
export const SUBMIT_WORK_SHIFT_BEGIN = "SUBMIT_WORK_SHIFT_BEGIN";
export const SUBMIT_WORK_SHIFT_SUCCESS = "SUBMIT_WORK_SHIFT_SUCCESS";
export const SUBMIT_WORK_SHIFT_ERROR = "SUBMIT_WORK_SHIFT_ERROR";
export const DELETE_WORK_SHIFT_BEGIN = "DELETE_WORK_SHIFT_BEGIN";
export const DELETE_WORK_SHIFT_SUCCESS = "DELETE_WORK_SHIFT_SUCCESS";
export const DELETE_WORK_SHIFT_ERROR = "DELETE_WORK_SHIFT_ERROR";


export const POST_REGISTRATION_BEGIN = "POST_REGISTRATION_BEGIN";
export const POST_REGISTRATION_SUCCESS = "POST_REGISTRATION_SUCCESS";
export const POST_REGISTRATION_ERROR = "POST_REGISTRATION_ERROR";

export const POST_LOGIN_BEGIN = "POST_LOGIN_BEGIN";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const RESET_STATE = "RESET";
