spring:
  datasource:
    username: #pass through environment variable SPRING_DATASOURCE_USERNAME
    password: #pass through environment variable SPRING_DATASOURCE_PASSWORD
    url: jdbc:postgresql://host:5432/dbname #pass through environment variable SPRING_DATASOURCE_URL
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: false
  mail:
    host: #pass through environment variable SPRING_MAIL_HOST
    protocol: smtps
    port: 465
    username: #pass through environment variable SPRING_MAIL_USERNAME
    password: #pass through environment variable SPRING_MAIL_PASSWORD
    test-connection: true
flyway:
  enabled: true
  locations: classpath:db/migration
  check-location: true
management:
  port: 8081
  security:
    enabled: false
app:
  api-origin: "https://api.host" #pass through environment variable APP_API_ORIGIN
  gui-origin: "https://host" #pass through environment variable APP_GUI_ORIGIN
  recaptcha:
    secret: #pass through environment variable APP_RECAPTCHA_SECRET
  jwt:
    header: Authorization
    secret: #pass through environment variable APP_JTW_SECRET
    expiration: 604800
  s3:
    access-key: #pass through environment variable APP_S3_ACCESS_KEY
    secret-key: #pass through environment variable APP_S3_SECRET_KEY
    region: eu_west_1
    bucket: #pass through environment variable APP_S3_BUCKET