spring:
  datasource:
    username: sa
    password:
    url: jdbc:hsqldb:mem:asmanager
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    show-sql: true
  mail:
    test-connection: false
flyway:
  enabled: false
  check-location: false
app:
  api-origin: "http://localhost:8080"
  gui-origin: "http://localhost:3000"
  jwt:
    secret: mySecret