spring:
  datasource:
    username: asmanager
    password: insecure
    url: jdbc:postgresql://localhost:5432/asmanager
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
flyway:
  enabled: true
app:
  api-origin: "http://localhost:8080"
  gui-origin: "http://localhost:3000"
  jwt:
    secret: mySecret
