spring:
  datasource:
    username: xxxx #pass through environment variable SPRING_DATASOURCE_USERNAME
    password: xxxx #pass through environment variable SPRING_DATASOURCE_PASSWORD
    url: jdbc:postgresql://host:5432/dbname #pass through environment variable SPRING_DATASOURCE_URL
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
jwt:
  header: Authorization
  secret: mySecret #pass through environment variable JTW_SECRET
  expiration: 604800
management:
  port: 8081
  security:
    enabled: false